const studentData = [
    {
        id          :    1,
        name        :   'Jweel',
        rool        :   25,
        reg         :   365562544154148,
        class       :   362,
        loocation   :   'Dhaka',
        image       :   'https://www.nilphamari.info/wp-content/uploads/2016/08/Sohel-Passport-Size-New-Photo.jpg',

        bangla      :   80,
        agreecuncer :   40,
        english     :   96,
        math        :   69,
        socialS     :   23,
        sicence     :   82,
        religons    :   60,
        commerce    :   80,
    },
    {
        id          :    2,
        name        :   'Achem',
        rool        :   30,
        reg         :   155562543040148,
        class       :   8,
        loocation   :   'Bhola',
        image       :   'https://i.ibb.co/G5yyssZ/Scuare.jpg',

        bangla      :   50,
        agreecuncer :   90,
        english     :   88,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   78,
    },
    {
        id          :    3,
        name        :   'Rana',
        rool        :   40,
        reg         :   225562544542248,
        class       :   9,
        loocation   :   'Khulna',
        image       :   'http://1.bp.blogspot.com/-vdi34NMKeQo/Urcomf2Jh9I/AAAAAAAAAFs/wv0JOotax64/s1600/passport+size+copy.jpg',

        bangla      :   98,
        agreecuncer :   98,
        english     :   63,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   89,
    },
    {
        id          :    4,
        name        :   'Sweety',
        rool        :   21,
        reg         :   95562542948,
        class       :   7,
        loocation   :   'Kurigram',
        image       :   'https://i.ibb.co/6ZQ01rM/Achem.jpg',

        bangla      :   75,
        agreecuncer :   60,
        english     :   48,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   32,
    },
    {
        id          :    5,
        name        :   'Rayhan',
        rool        :   41,
        reg         :   75562544748,
        class       :   8,
        loocation   :   'Rangpur',
        image       :   'https://wub.edu.bd/admin-assets/images/employeeImg_thumb/passport_size_photo_(white_background).jpg',

        bangla      :   93,
        agreecuncer :   45,
        english     :   69,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   30,
    },
    {
        id          :    6,
        name        :   'ashraf',
        rool        :   23,
        reg         :   855625423148,
        class       :   8,
        loocation   :   'Dinajpur',
        image       :   'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSecnvbdtzRm4e2tLO7bx7FQ-mWFGW5toF-ndeLOPjrNDh2voy3C1fBbyIozOTfxG1I7Sc&usqp=CAU',

        bangla      :   96,
        agreecuncer :   46,
        english     :   78,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   45,
    },
    {
        id          :    7,
        name        :   'Arafat',
        rool        :   62,
        reg         :   2555625465148,
        class       :   7,
        loocation   :   'Khulna',
        image       :   'https://ssl.du.ac.bd/fontView/assets/department_image/dept_chairman_AQF-1615045086.JPG',

        bangla      :   50,
        agreecuncer :   50,
        english     :   69,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   63,
    },
    {
        id          :    8,
        name        :   'Mahi',
        rool        :   29,
        reg         :   7355625429148,
        class       :   9,
        loocation   :   'Savar',
        image       :   'https://hometutorbd.com/profile-image/photograph/1077_Passport%20Photo.jpg',

        bangla      :   48,
        agreecuncer :   66,
        english     :   78,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   48,
    },
    {
        id          :    9,
        name        :   'Nahid',
        rool        :   52,
        reg         :   955625452148,
        class       :   8,
        loocation   :   'Gazipur',
        image       :   'http://shipboardtraining.com/resources/thumb-female.845dfe89.jpg',

        bangla      :   59,
        agreecuncer :   97,
        english     :   36,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   78,
    },
    {
        id          :    10,
        name        :   'Sabbir',
        rool        :   25,
        reg         :   855625465148,
        class       :   7,
        loocation   :   'CTG',
        image       :   'http://shipboardtraining.com/resources/thumb-female.845dfe89.jpg',

        bangla      :   77,
        agreecuncer :   89,
        english     :   36,
        math        :   69,
        socialS     :   98,
        sicence     :   82,
        religons    :   60,
        commerce    :   79,
    },

]